[0.279s] Invoking command in '/home/advay/mrt/build/tutorial_interfaces': /usr/bin/cmake --build /home/advay/mrt/build/tutorial_interfaces -- -j4 -l4
[0.335s] -- Found ament_cmake: 1.3.6 (/opt/ros/humble/share/ament_cmake/cmake)
[0.730s] -- Found geometry_msgs: 4.2.3 (/opt/ros/humble/share/geometry_msgs/cmake)
[0.794s] -- Found rosidl_generator_c: 3.1.5 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.800s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.816s] -- Found rosidl_generator_cpp: 3.1.5 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.848s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.896s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.215s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[1.818s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[1.818s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[1.819s]   tutorial_interfaces --arguments-file
[1.819s]   /home/advay/mrt/build/tutorial_interfaces/rosidl_adapter__arguments__tutorial_interfaces.json
[1.819s]   --output-dir
[1.820s]   /home/advay/mrt/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces
[1.820s]   --output-file
[1.820s]   /home/advay/mrt/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces.idls)
[1.821s]   returned error code 1:
[1.821s] 
[1.821s]   Error processing 'sensor_msgs image' of 'tutorial_interfaces/Aruco':
[1.822s]   ''sensor_msgs' is an invalid message name.  It should have the pattern
[1.822s]   '^[A-Z][A-Za-z0-9]*$''
[1.822s] 
[1.823s]   Traceback (most recent call last):
[1.823s] 
[1.824s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[1.824s]       return _run_code(code, main_globals, None,
[1.824s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[1.825s]       exec(code, run_globals)
[1.825s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.825s]       sys.exit(main())
[1.826s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[1.826s]       abs_idl_file = convert_to_idl(
[1.826s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.827s]       return convert_msg_to_idl(
[1.827s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.827s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.828s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
[1.828s]       Type(type_string, context_package_name=pkg_name),
[1.829s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
[1.829s]       super(Type, self).__init__(
[1.829s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[1.830s]       raise InvalidResourceName(
[1.830s] 
[1.830s]   rosidl_adapter.parser.InvalidResourceName: 'sensor_msgs' is an invalid
[1.831s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.831s] 
[1.831s] Call Stack (most recent call first):
[1.832s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.832s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[1.833s] 
[1.833s] [0m
[1.833s] -- Configuring incomplete, errors occurred!
[1.834s] See also "/home/advay/mrt/build/tutorial_interfaces/CMakeFiles/CMakeOutput.log".
[1.837s] gmake: *** [Makefile:1179: cmake_check_build_system] Error 1
[1.844s] Invoked command in '/home/advay/mrt/build/tutorial_interfaces' returned '2': /usr/bin/cmake --build /home/advay/mrt/build/tutorial_interfaces -- -j4 -l4
